version: "3.6"

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: sh -c "npx vite --host 0.0.0.0 --port 80"
    ports: 
      - 80:80
    restart: unless-stopped

