version: "3.6"

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports: 
      - 28080:80
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

